
import "./style.css"

import user1 from "../../img/custumers/elon.webp"
import user2 from "../../img/custumers/iris.webp"
import user3 from "../../img/custumers/joey.webp"
import user4 from "../../img/custumers/joseph.webp"
import user5 from "../../img/custumers/philip.webp"
import user6 from "../../img/custumers/rick.webp"
import { Link, Outlet, useOutletContext } from "react-router-dom"
import { FaArrowCircleLeft, FaArrowCircleRight, FaStar, FaStarHalf } from "react-icons/fa"
import { useEffect } from "react"

const Five_star = ()=>{
    return(
        <div>
            <FaStar color="gold"/>
            <FaStar color="gold"/>
            <FaStar color="gold"/>
            <FaStar color="gold"/>
            <FaStar color="gold"/>
        </div>
    )
}

const For_alf_star = ()=>{
    return(
        <div>
            <FaStar color="gold"/>
            <FaStar color="gold"/>
            <FaStar color="gold"/>
            <FaStar color="gold"/>
            <FaStar/>
        </div>
    )
}

const User = (props)=>{
    return(
        <div className="custumer">
            <div>
                <div className="profile">
                    <div className="logo"><img src={props.img}/></div>
                    <div className="name">
                        <p><strong>{props.name}</strong></p>
                        <ul>
                            {props.star}
                        </ul>
                    </div>
                </div>
                <p>{props.text}</p>
            </div>
        </div>
    )
}

//PARA TEMPLATE EM INGLES
export const User1 = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user6")
        setRota("user2")
    },[])
    return <User name = "Gabriel" img = {user1} star = {<Five_star/>} text = "As a video production company, the speed and ease of use of this service are incredible. We can now add professional narrations to our projects without having to schedule recording sessions or hire external voice actors. Additionally, the quality of the voices is exceptional. Highly recommended!"/>
}

export const User2 = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("")
        setRota("user3")
    },[])
    return <User name = "Iris" img = {user2} star = {<Five_star/>} text = "Our advertising agency has experienced a significant increase in audience engagement since we started using the voices generated by this service. The radio ads have a much greater impact, and our clients are extremely satisfied with the results. It's an incredible tool!"/>
}

export const User3 = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user2")
        setRota("user4")
    },[])
    return <User name = "Joey" img = {user3} star = {<Five_star/>} text = "Our e-learning company has seen a significant improvement in student engagement since we started using the voices generated by this service in our online courses. Students have reported better understanding and a more immersive experience. We are very pleased with the results and will continue to use this solution!"/>
}

export const User4 = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user3")
        setRota("user5")
    },[])
    return <User name = "Joseph" img = {user4} star = {<For_alf_star/>} text = "I wrote an audiobook and was looking for a way to bring the characters to life and make the story more engaging for listeners. With the help of this service, the voices of the characters gained authenticity and emotion. Listeners loved it, and audiobook sales increased significantly. I'm very happy with the results!"/>
}

export const User5 = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user4")
        setRota("user6")
    },[])
    return <User name = "Philip" img = {user5} star = {<Five_star/>} text = "I'm impressed with the quality of the voices generated by the service. The narrations are extremely realistic and have added a professional touch to my videos. Now I can create captivating content without having to hire external voice actors. Highly recommended!"/>
}

export const User6 = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user5")
        setRota("")
    },[])
    return <User name = "Rick" img = {user6} star = {<For_alf_star/>} text = "I'm amazed at how this service has made our automated customer support system friendlier and more interactive. The generated voices sound human and natural, and our customers appreciate the experience of receiving voice responses. We are very satisfied with the results and have received positive feedback from users."/>
}

//PARA TEMPLATE EM PORTUGUES
export const User1_pt = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user6")
        setRota("user2")
    },[])
    return <User name = "Gabriel" img = {user1} star = {<Five_star/>} text = "Como produtor de vídeos, a rapidez e facilidade de uso desse serviço são incríveis. Agora podemos adicionar narrações profissionais aos nossos projetos sem precisar agendar sessões de gravação e contratar locutores externos. Além disso, a qualidade das vozes é excepcional. Recomendamos fortemente!"/>
}

export const User2_pt = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("")
        setRota("user3")
    },[])
    return <User name = "Iris" img = {user2} star = {<Five_star/>} text = "Nossa agência de publicidade experimentou um aumento significativo no envolvimento do público desde que começamos a usar as vozes geradas por esse serviço. Os anúncios de rádio têm um impacto muito maior e nossos clientes estão extremamente satisfeitos com os resultados. É uma ferramenta incrível!"/>
}

export const User3_pt = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user2")
        setRota("user4")
    },[])
    return <User name = "Joey" img = {user3} star = {<Five_star/>} text = "Nossa empresa de e-learning viu uma melhoria significativa no engajamento dos alunos desde que começamos a usar as vozes geradas por esse serviço em nossos cursos online. Os alunos relataram uma melhor compreensão e uma experiência mais imersiva. Estamos muito satisfeitos com os resultados e continuaremos usando essa solução!"/>
}

export const User4_pt = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user3")
        setRota("user5")
    },[])
    return <User name = "Joseph" img = {user4} star = {<For_alf_star/>} text = "Eu escrevi um audiobook e estava procurando uma maneira de dar vida aos personagens e tornar a história mais envolvente para os ouvintes. Com a ajuda desse serviço, as vozes dos personagens ganharam autenticidade e emoção. Os ouvintes adoraram e as vendas do audiobook aumentaram consideravelmente. Estou muito feliz com os resultados!"/>
}

export const User5_pt = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user4")
        setRota("user6")
    },[])
    return <User name = "Philip" img = {user5} star = {<Five_star/>} text = "Estou impressionado com a qualidade das vozes geradas pelo serviço. As locuções são extremamente realistas e adicionaram um toque profissional aos meus vídeos. Agora posso criar conteúdo cativante sem precisar contratar locutores externos. Recomendo!"/>
}

export const User6_pt = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user5")
        setRota("")
    },[])
    return <User name = "Rick" img = {user6} star = {<For_alf_star/>} text = "Estou maravilhado com a capacidade desse serviço de tornar nosso sistema de atendimento automatizado mais amigável e interativo. As vozes geradas soam humanas e naturais, e nossos clientes apreciam a experiência de receber respostas por voz. Estamos muito satisfeitos com os resultados e recebemos feedback positivo dos usuários."/>
}

//PARA TEMPLATE EM ESPANHOL
export const User1_es = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user6")
        setRota("user2")
    },[])
    return <User name = "Gabriel" img = {user1} star = {<Five_star/>} text = "Como empresa de producción de videos, la rapidez y facilidad de uso de este servicio son increíbles. Ahora podemos agregar narraciones profesionales a nuestros proyectos sin tener que programar sesiones de grabación ni contratar actores de voz externos. Además, la calidad de las voces es excepcional. ¡Muy recomendable!"/>
}

export const User2_es = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("")
        setRota("user3")
    },[])
    return <User name = "Iris" img = {user2} star = {<Five_star/>} text = "Nuestra agencia de publicidad ha experimentado un aumento significativo en la participación del público desde que comenzamos a utilizar las voces generadas por este servicio. Los anuncios de radio tienen un impacto mucho mayor y nuestros clientes están extremadamente satisfechos con los resultados. ¡Es una herramienta increíble!"/>
}

export const User3_es = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user2")
        setRota("user4")
    },[])
    return <User name = "Joey" img = {user3} star = {<Five_star/>} text = "Nuestra empresa de e-learning ha visto una mejora significativa en la participación de los estudiantes desde que comenzamos a utilizar las voces generadas por este servicio en nuestros cursos en línea. Los estudiantes han informado una mejor comprensión y una experiencia más inmersiva. ¡Estamos muy satisfechos con los resultados y seguiremos utilizando esta solución!"/>
}

export const User4_es = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user3")
        setRota("user5")
    },[])
    return <User name = "Joseph" img = {user4} star = {<For_alf_star/>} text = "Escribí un audiolibro y estaba buscando una forma de dar vida a los personajes y hacer que la historia fuera más atractiva para los oyentes. Con la ayuda de este servicio, las voces de los personajes adquirieron autenticidad y emoción. Los oyentes quedaron encantados y las ventas del audiolibro aumentaron considerablemente. ¡Estoy muy contenta con los resultados!"/>
}

export const User5_es = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user4")
        setRota("user6")
    },[])
    return <User name = "Philip" img = {user5} star = {<Five_star/>} text = "Estoy impresionado con la calidad de las voces generadas por el servicio. Las locuciones son extremadamente realistas y le han dado un toque profesional a mis videos. Ahora puedo crear contenido cautivador sin tener que contratar actores de voz externos. ¡Altamente recomendado!"/>
}

export const User6_es = ()=>{
    const [setRota, setBefore] = useOutletContext()
    useEffect(()=>{
        setBefore("user5")
        setRota("")
    },[])
    return <User name = "Rick" img = {user6} star = {<For_alf_star/>} text = "Estoy asombrado de cómo este servicio ha mejorado nuestro sistema de soporte al cliente automatizado haciéndolo más amigable e interactivo. Las voces generadas suenan humanas y naturales, y nuestros clientes aprecian la experiencia de recibir respuestas de voz. Estamos muy satisfechos con los resultados y hemos recibido comentarios positivos de los usuarios."/>
}

